### ISSUE TITLE
Error running test: error unmarshalling response: json: cannot unmarshal object into Go value of type

### ISSUE THREAD

**Issue by Convizr** [xavidop/voiceflow-cli#23]
### What happened?

When trying to run a test using the YAML files the CLI immediatly gives this error. I'm creating a web app to make it easier to automate tests. The issue can be related to my web app or the CLI. I hope to rule out one or the other.

> Error running test: error unmarshalling response: json: cannot unmarshal object into Go value of type

### How can we reproduce this?

I created a test agent with some easy responses, you can get the agent here [https://creator.voiceflow.com/dashboard?import=682dbb72e52f734c295445c0](url)

Use the test files from the zip below and try to run it in the CLI. 
[YAML Files.zip](https://github.com/user-attachments/files/20398424/YAML.Files.zip)

### voiceflow version

```bash
1.15.0
```

### Search

- [x] I did search for other open and closed issues before opening this.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by xavidop** [comment]
working on it

**Comment by xavidop** [comment]
After debugging it, I found that the suite spec was wrong. the `environment` specified does not exist. It should be either `development` or `production`. The test spec file was also wrong, you missed the launch step. Here is the file that worked for me:

1. Suite:
```yaml
name: Test Session - 5/21/2025sdssds
description: Auto-generated suite from UI recording
environmentName: development
tests:
  - id: generated_test
    file: converted_test.yaml
```

2. tests:
```yaml
name: Test Session - 5/21/2025sdssds
description: 'Auto-generated test from UI recording, converted to interactions format.'
interactions:
  - id: interaction_1
    user:
      type: launch
    agent:
      validate:
        - type: contains
          value: "Hey"
  - id: interaction_2
    user:
      type: text
      text: hey
    agent:
      validate:
        - type: contains
          value: "Hey! How’s it going?"
  - id: interaction_3
    user:
      type: text
      text: bye
    agent:
      validate:
        - type: contains
          value: "Bye"
```
